version: "3.9"

services:
  ingest:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    ports:
    - "5678:5678"  # Expose debugger port
    volumes:
      - ./crawler/ingest:/app/ingest
      - scholarship_volumn:/scholarship   
    command: [] 
    restart: "on-failure"

volumes:
  scholarship_volumn:
    external : true
